---
title: "Budgie INBRE stress and contact calls"
author: <center><font size="4"><a href="http://marceloarayasalas.weebly.com/">Marcelo Araya-Salas PhD</a> & <a href="https://wrightbehaviorlab.org/">Timothy Wright PhD</a></font></center>
output: github_document
date: <center>`r format(Sys.Date(), "%d-%m-%Y")`</center>
editor_options:
  chunk_output_type: console
---

<!-- Description  -->
Inducing different levels of stress on budgie males to infer any stress related variation in contact call structure

*Updated on `r Sys.time()`*

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}

# install.packages("rmarkdown")
library(rmarkdown)

knitr::opts_chunk$set(
  collapse = TRUE,
  out.width = "100%"
)
```

## Table of contents
* [Experimental design](#experimental-design)
  * [Research questions](#research-questions)
    * [Analyses](#Analyses)
      * [To do list](#to-do-list)
        * [Contact](#contact)


## Experimental design 

- 3 round with repeated treatments
- No repeated measurements across rounds (bird found only in 1 round)
- 3 levels of stress
- Each round last 3 weeks
- each birds was present in a single treatment
- 4 groups on each round (birds from the same group were from the same source room)
- All subjects were males

## Research questions

- Do acoustic parameters differ between the 3 stress treatments? 
	- This can be ask for each week independently (check if pattern is more pronounced as time goes by)
	- Higher entropy, higher frequency in stress birds
	- Focus on more biologically meaningful parameters: energy distribution, frequency and duration as well as a PCA on those parameters
	
- Does stress affect the ability to learn contact calls?
	- Flock level acoustic convergence
	- Do individuals move more across the acoustic space over time and is it related to treatment?


## Analysis

* Automatic detection of all contact calls (MAS)
* [Determining best measuring method for quantifying acoustic structure in budgie contact calls](https://rpubs.com/marcelo-araya-salas/785368) (MAS)
* Measuring acoustic parameters on contact calls (MAS) 
* [Variation in vocal behavior under varying stress levels](https://rpubs.com/marcelo-araya-salas/786522)

## In progress
* Stats on variation in frequency and time call parameters related to increased stress (MAS)

## To-do list

## In progress

-   Stats on variation in frequency and time call parameters related to
    increased stress 

## To-do list

-   Ignore week 5
-   Acoustic space estimation 
-   Physiology parameters relative to baseline 
-   Try exploratory graphs first 
-   Acoustic space compare to baseline (week 1)
-   Use Kernel density for overlap measurements 
-   Try log curve fitting on sample size vs acoustics space plot
-   Calculate individual overlap to its own group and use regular regression
-   Split previous measurements by week
-   Change in overlap with self over time
-   Acoustic space accumulation curve by individual group by treatment 

## Status
Project is: _in progress_

## Contact
Created by [Marcelo Araya-Salas](https://marceloarayasalas.weebly.com/)

